config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mymoives do
    member do
      post :like
      post :cancle
    end

    resources :reviews
  end

  namespace :account do
    resources :mymoives
    resources :reviews
  end
  root 'mymoives#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mymoive.rb
class Mymoive < ApplicationRecord
  belongs_to :user
  has_many :reviews
  validates :name, presence: true

  has_many :mymoive_relationships
  has_many :members,through: :mymoive_relationships, source: :user
end

app/models/mymoive_relationship.rb
class MymoiveRelationship < ApplicationRecord
  belongs_to :mymoive
  belongs_to :user

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :mymoive

  validates :content, presence: true
  scope :recent, -> { order("created_at DESC") }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :mymoives
  has_many :reviews

  has_many :mymoive_relationships
  has_many :reviewed_mymoives, :through => :mymoive_relationships, :source => :mymoive

  def is_favorite_of?(mymoive)
    reviewed_mymoives.include?(mymoive)
  end

  def like!(mymoive)
    reviewed_mymoives << mymoive
  end

  def cancle!(mymoive)
    reviewed_mymoives.delete(mymoive)
  end

end

app/controllers/account/mymoives_controller.rb
class Account::MymoivesController < ApplicationController
    before_action :authenticate_user!

    def index
      @mymoives = current_user.reviewed_mymoives
    end

end

app/controllers/account/reviews_controller.rb
class Account::ReviewsController < ApplicationController
  before_action :authenticate_user!
  def index
    @reviews = current_user.reviews
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mymoives_controller.rb
class MymoivesController < ApplicationController
   before_action :authenticate_user! , only: [:new,:create,:edit,:update,:destroy,:like,:cancle]
   before_action :find_mymoive_and_check_permission, only: [:edit,:update,:destroy]

  def index
    @mymoives = Mymoive.all
  end

  def new
    @mymoive = Mymoive.new
  end

  def create
    @mymoive = Mymoive.new(mymoive_params)
    @mymoive.user = current_user
    if @mymoive.save
      current_user.like!(@mymoive)
      redirect_to mymoives_path
    else
      render :new
    end
  end

  def show
    @mymoive = Mymoive.find(params[:id])
    @reviews = @mymoive.reviews.recent.paginate(:page => params[:page], :per_page => 3)
  end

  def edit

  end

  def update

    if @mymoive.update(mymoive_params)
      redirect_to mymoives_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy

    @mymoive.destroy
    redirect_to mymoives_path, alert: "Delete moive Success"
  end

  def like
   @mymoive = Mymoive.find(params[:id])

    if !current_user.is_favorite_of?(@mymoive)
      current_user.like!(@mymoive)
      flash[:notice] = "收藏影片成功！"
    else
      flash[:warning] = "该影片已收藏过"
    end

    redirect_to mymoife_path(@mymoive)
  end

  def cancle
    @mymoive = Mymoive.find(params[:id])

    if current_user.is_favorite_of?(@mymoive)
      current_user.cancle!(@mymoive)
      flash[:alert] = "已取消收藏！"
    else
      flash[:warning] = "从未收藏过，怎么取消？"
    end

    redirect_to mymoife_path(@mymoive)
  end

  private


  def find_mymoive_and_check_permission
    @mymoive = Mymoive.find(params[:id])
    if current_user != @mymoive.user
      redirect_to root_path, alert: "You have no permission."
    end
  end

  def mymoive_params
    params.require(:mymoive).permit(:name,:description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create,:edit,:update,:destroy]
  before_action :check_is_favorite_of_moive, only: [:new,:edit,:destroy]

  def new

    @review = Review.new
  end

  def create
    @mymoive = Mymoive.find(params[:mymoife_id])
    @review = Review.new(review_params)
    @review.mymoive = @mymoive
    @review.user = current_user

    if @review.save
      redirect_to mymoife_path(@mymoive)
    else
      render :new
    end
  end


  def edit

    @review = Review.find(params[:id])
  end

  def update
    @mymoive = Mymoive.find(params[:mymoife_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to account_reviews_path, notice: "Update Review Success"
    else
      :edit
    end
  end

  def destroy

    @review = Review.find(params[:id])
    @review.destroy
    redirect_to account_reviews_path, alert: "Deleted Review Success"
  end

  private

  def check_is_favorite_of_moive
    @mymoive = Mymoive.find(params[:mymoife_id])
    if !current_user.is_favorite_of?(@mymoive)
      redirect_to root_path, alert: "必须收藏影片才可以进行评价."
    end
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
  end
end

app/helpers/account/mymoives_helper.rb
module Account::MymoivesHelper
end

app/helpers/account/reviews_helper.rb
module Account::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/mymoives_helper.rb
module MymoivesHelper
  def render_mymoive_description(mymoive)
    simple_format(mymoive.description)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Moive Review
        <br>Design by Louis

    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Moive Review</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">

                                <% if !current_user %>
                                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                                  <li><%= link_to("登录", new_user_session_path) %></li>
                                <% else %>
                                  <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        Hi!, <%= current_user.email %>
                                        <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                          <li> <%= link_to("我收藏的电影", account_mymoives_path) %></li>
                                          <li> <%= link_to("我的影评", account_reviews_path) %></li>
                                          <li class="divider"> </li>
                                        <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                                    </ul>
                                  </li>
                                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoiveReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
        <%= render "common/navbar" %>
        <%= render "common/flashes" %>
        <%= yield %>
    </div>

    <%= render "common/footer" %>
  </body>
</html>

app/views/mymoives/_form.html.erb
<%= simple_form_for @mymoive do |f| %>
  <div class="form-mymoive">
    <%= f.input :name, input_html: {class: "form-control"} %>
    <%= f.input :description, input_html: {class: "form-control"} %>
  </div>

<%= f.submit "Submit", class: "btn btn-primary", data:{ disable_with: "Submiting..." } %>
<% end %>

app/views/mymoives/_mymoive_item.html.erb
<% @mymoives.each do |mymoive| %>
  <tr>
    <td>#</td>
    <td><%= link_to(mymoive.name, mymoife_path(mymoive)) %></td>
    <td><%= render_mymoive_description(mymoive) %></td>
    <td><%= mymoive.user.email %></td>
    <td>
      <% if current_user && current_user == mymoive.user %>
        <%= link_to("Edit", edit_mymoife_path(mymoive), class: "btn btn-sm btn-default")%>
        <%= link_to("Delete", mymoife_path(mymoive),    class: "btn btn-sm btn-default",
                    method: :delete, data: { confirm: "Are you sure?" } )%>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/mymoives/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑影片</h2>

    <hr>
    <%= render "form" %>

</div>

app/views/mymoives/index.html.erb
<div class="col-md-12">
  <div class="mymoive">
    <%= link_to("New moive", new_mymoife_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>影片名</td>
        <td>简介</td>
        <td>导演</td>
      </tr>
    </thead>
    <tbody>
      <% @mymoives.each do |mymoive| %>
        <tr>
          <td>#</td>
          <td><%= link_to(mymoive.name, mymoife_path(mymoive)) %></td>
          <td><%= render_mymoive_description(mymoive) %></td>
          <td><%= mymoive.user.email %></td>
          <td>
            <% if current_user && current_user == mymoive.user %>
              <%= link_to("Edit", edit_mymoife_path(mymoive), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", mymoife_path(mymoive),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/mymoives/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增电影</h2>

    <hr>
    <%= render "form" %>

</div>

app/views/mymoives/show.html.erb
<div class="col-md-12">
  <div class="mymoive">
    <span class="pull-right">
      <% if current_user && current_user.is_favorite_of?(@mymoive) %>
        <label class="label label-success"> 已收藏 </label>
        <%= link_to("取消收藏", cancle_mymoife_path(@mymoive), method: :post, class: "btn btn-default") %>
      <% else %>
        <label class="label label-warning"> 未收藏 </label>
        <%= link_to("收藏影片", like_mymoife_path(@mymoive), method: :post, class: "btn btn-default") %>
      <% end %>
    </span>

    <%= link_to("写影评", new_mymoife_review_path(@mymoive), class: "btn btn-default pull-right")%>

    <% if current_user && current_user == @mymoive.user %>
      <%= link_to("编辑", edit_mymoife_path(@mymoive), class: "btn btn-primary pull-right")%>
    <% end %>
  </div>
  <h2><%= @mymoive.name %></h2>
  <p><%= @mymoive.description %></p>

  <table class="table">
    <thead>
     <tr>
        <th>评价内容</th>
        <th>评价者</th>
        <th>评价时间</th>
      </tr>
    </thead>
    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td><%= review.content %></td>
          <td><%= review.user.email %></td>
          <td><%= review.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= will_paginate @reviews %>
  </div>
</div>

app/views/reviews/edit.html.erb
\<h2 class="text-center">修改影评</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@mymoive,@review] do |f| %>
    <div class="form-mymoive">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h2 class="text-center">新增影评</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@mymoive,@review] do |f| %>
    <div class="form-mymoive">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1> Hello World! </h1>